import srcsetFiles from "virtual:srcset-manifest";
import imageDims from "virtual:image-dims";

/**
 * Image widths generated by scripts/optimize-images.mjs and consumed
 * everywhere srcset is built.
 *
 * `320` was added after Lighthouse flagged ~150 KiB of waste on the home
 * page: small album thumbnails (landscape covers like product-bread) were
 * being served the `@768` variant for ~285px-wide display because the
 * 480/768/1080 ladder had nothing smaller. With `@320` in the rotation,
 * the browser's auto-srcset picker now lands on `@320` for these
 * small-displayed images on mobile DPR-1 emulators while still
 * upgrading to `@768` or `@1080` on real high-DPI devices.
 */
export const SRCSET_WIDTHS = [320, 480, 768, 1080] as const;

/**
 * Build a srcset attribute string for responsive images. By default returns
 * variants in the source's own format (webp/jpg/png); pass a `forceExt` to
 * emit a srcset for a sibling format like AVIF if available.
 * @param src - Public image path (must start with `/media/`).
 * @param widths - Widths to include in the srcset.
 * @param forceExt - Optional override extension (e.g. ".avif") to emit a
 *   srcset for that variant set rather than the source format.
 * @returns A srcset string, or empty string if no variants are available.
 */
export function imgSrcset(
  src: string,
  widths: readonly number[] = SRCSET_WIDTHS,
  forceExt?: string,
): string {
  if (!src.startsWith("/media/") || widths.length === 0) return "";
  const dot = src.lastIndexOf(".");
  const ext = forceExt ?? src.substring(dot);
  const base = src.substring(0, dot).replace("/media/", "/srcset/");
  const available = widths.filter((w) => srcsetFiles.has(`${base}@${w}${ext}`));
  if (available.length === 0) return "";
  return available.map((w) => `${base}@${w}${ext} ${w}w`).join(", ");
}

/**
 * Look up the natural pixel dimensions of an image under `/media/`. Populated at
 * build time by the `virtual:image-dims` vite plugin (sharp-based measurement).
 * Callers use these to set `width`/`height` on `<img>` so lazy-loaded media
 * reserves its aspect-ratio box and doesn't cause CLS.
 * @param src - Public image path, e.g. "/media/album-foo.webp".
 * @returns Tuple `[width, height]` in pixels, or undefined if not measured.
 */
export function imgDims(src: string): [number, number] | undefined {
  return imageDims.get(src);
}
