import adapter from "@sveltejs/adapter-static";
import { mdsvex } from "mdsvex";
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

/** SvelteKit configuration with static adapter, mdsvex, and prerender settings. */
const config = {
  extensions: [".svelte", ".svx", ".md"],
  preprocess: [vitePreprocess(), mdsvex({ extensions: [".svx", ".md"] })],
  kit: {
    adapter: adapter({
      pages: "dist",
      assets: "dist",
      precompress: false,
      strict: true,
      fallback: "404.html",
    }),
    paths: {
      base: "",
    },
    prerender: {
      handleHttpError: "fail",
      // Entry list is generated by the catch-all `[lang=lang]/[...slug]/+page.ts` via
      // getAllPageEntries(), plus "*" picks up the home and sitemap routes.
      entries: ["*"],
    },
  },
};

export default config;
